# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrecord',
            old_name='name',
            new_name='webpage',
        ),
    ]
